# Generated by Django 2.2.1 on 2019-05-05 09:22

from django.db import migrations, models
import django.db.models.deletion
import omr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_num', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('set_img_url', models.URLField(blank=True, null=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='omr.Theme')),
            ],
            options={
                'ordering': ['set_num'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(help_text='Full model number including suffix, e.g. 8110-1', max_length=50)),
                ('is_main_model', models.BooleanField(default=True)),
                ('alternate_model', models.CharField(blank=True, max_length=100, null=True)),
                ('missing_parts', models.BooleanField(default=False)),
                ('missing_patterns', models.BooleanField(default=False)),
                ('missing_stickers', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=omr.models.CustomStorage(), upload_to=omr.models.File.file_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='omr.Author')),
                ('model', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='omr.Set')),
            ],
            options={
                'ordering': ['model'],
            },
        ),
    ]
